version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - pnpm --dir=frontend install --frozen-lockfile
    - pnpm --dir=frontend run build
    - rm -rf internal/server/assets/*
    - cp -av frontend/dist/* internal/server/assets

builds:
  - env:
      - CGO_ENABLED=0
    tags:
      - assets
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
    - ghcr.io/rfwatson/octoplex:latest-amd64
    - ghcr.io/rfwatson/octoplex:{{ .Tag }}-amd64
    use: buildx
    goarch: amd64
    dockerfile: ./Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
    - ghcr.io/rfwatson/octoplex:latest-arm64
    - ghcr.io/rfwatson/octoplex:{{ .Tag }}-arm64
    use: buildx
    goarch: arm64
    dockerfile: ./Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/rfwatson/octoplex:{{ .Tag }}"
    image_templates:
      - ghcr.io/rfwatson/octoplex:{{ .Tag }}-amd64
      - ghcr.io/rfwatson/octoplex:{{ .Tag }}-arm64
  - name_template: "ghcr.io/rfwatson/octoplex:latest"
    image_templates:
      - ghcr.io/rfwatson/octoplex:latest-amd64
      - ghcr.io/rfwatson/octoplex:latest-arm64

brews:
  - name: octoplex
    description: "Octoplex is a live video restreamer for the terminal."
    homepage: "https://github.com/rfwatson/octoplex"
    repository:
        owner: rfwatson
        name: homebrew-octoplex
        token: "{{ .Env.HOMEBREW_TOKEN }}"
    install: |
      bin.install "octoplex"
    test: |
      system "#{bin}/octoplex -h"

release:
  draft: true
  github:
    owner: rfwatson
    name: octoplex

changelog:
  use: github
  groups:
    - title: New Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Refactorings"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^doc:"
      - "^test:"
      - "^ci:"
      - typo
