version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      # - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: octoplex
    description: "Octoplex is a live video restreamer for the terminal."
    homepage: "https://github.com/rfwatson/octoplex"
    repository:
        owner: rfwatson
        name: homebrew-octoplex
    install: |
      bin.install "octoplex"
    test: |
      system "#{bin}/octoplex -h"

release:
  github:
    owner: rfwatson
    name: octoplex

changelog:
  use: github
  filters:
    exclude:
      - "^doc:"
      - "^test:"
      - "^ci:"
      - typo
