with-expecter: true
dir: ./internal/generated/mocks/{{ replaceAll .InterfaceDirRelative "internal/" "" }}
filename: "{{ .InterfaceName | lower }}_mock.go"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
issue-845-fix: true
resolve-type-alias: false
packages:
  git.netflux.io/rob/octoplex/internal/server:
    interfaces:
      TokenStore:
  git.netflux.io/rob/octoplex/internal/container:
    interfaces:
      DockerClient:
  git.netflux.io/rob/octoplex/internal/mediaserver:
    interfaces:
      httpClient:
        config:
          mockname: HTTPClient
