---
services:
  octoplex:
    image: ghcr.io/rfwatson/octoplex:latest
    container_name: octoplex
    restart: unless-stopped
    volumes:
      - octoplex-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OCTO_LISTEN_ADDR: "[::]:8443" # bind to all network interfaces
    ports:
      - "8443:8443"
volumes:
  octoplex-data:
    driver: local
