[env]
GOTOOLCHAIN = "go1.24.3"
CGO_ENABLED = "0"

[tasks.test]
description = "Run tests"
dir = "{{cwd}}"
run = "go test -v ./..."
alias = "t"

[tasks.test_integration]
description = "Run integration tests"
dir = "{{cwd}}"
run = "go test -v -count 1 -p 1 -tags=integration -run TestIntegration ./..."
alias = "ti"

[tasks.test_ci]
description = "Run tests in CI"
dir = "{{cwd}}"
run = "go test -v -count 1 -race ./..."
env = { CGO_ENABLED = "1" }

[tasks.test_integration_ci]
description = "Run integration tests in CI"
dir = "{{cwd}}"
run = "go test -v -count 1 -race -p 1 -tags=integration -run TestIntegration ./..."
env = { CGO_ENABLED = "1" }

[tasks.lint]
description = "Run linters"
dir = "{{cwd}}"
run = "golangci-lint run"
alias = "l"

[tasks.fmt]
description = "Run formatter"
dir = "{{cwd}}"
run = "goimports -w ."
alias = "f"

[tasks.generate_mocks]
description = "Generate mocks"
dir = "{{cwd}}"
run = "go tool mockery"
alias = "m"

[tasks.generate_proto]
description = "Generate gRPC files from proto"
dir = "{{cwd}}"
run = "protoc -I proto --go_out=paths=source_relative:internal/generated/grpc --go-grpc_out=paths=source_relative:internal/generated/grpc proto/api.proto proto/domain.proto proto/event.proto proto/command.proto"
alias = "p"
