[env]
GOTOOLCHAIN = "go1.24.2"

[tasks.test]
description = "Run tests"
dir = "{{cwd}}"
run = "go test -v ./..."
alias = "t"

[tasks.test_integration]
description = "Run integration tests"
dir = "{{cwd}}"
run = "go test -v -count 1 -p 1 -tags=integration -run TestIntegration ./..."
alias = "ti"

[tasks.test_ci]
description = "Run tests in CI"
dir = "{{cwd}}"
run = "go test -v -count 1 -race ./..."

[tasks.test_integration_ci]
description = "Run integration tests in CI"
dir = "{{cwd}}"
run = "go test -v -count 1 -race -p 1 -tags=integration -run TestIntegration ./..."

[tasks.lint]
description = "Run linters"
dir = "{{cwd}}"
run = "golangci-lint run"
alias = "l"

[tasks.generate_mocks]
description = "Generate mocks"
dir = "{{cwd}}"
run = "go tool mockery"
alias = "m"
