#!/usr/bin/env bash
#MISE description="Build assets ready for embedding in the main binary"

set -euo pipefail

pnpm --dir=frontend install
pnpm --dir=frontend build
rm -rf internal/server/assets/*
cp -av frontend/dist/* internal/server/assets
