#!/usr/bin/env bash
#MISE description="Check if go generate is up-to-date"

set -euo pipefail

go generate ./...
STATUS=$(git status --porcelain)
if [ -n "$STATUS" ]; then
    echo "Run \`go generate ./...\` and commit the changes."
    exit 1
fi

exit 0
