#!/usr/bin/env bash
#MISE description="Build and push mediamtx image"

set -euo pipefail

docker build -f build/mediamtx.Dockerfile -t netfluxio/mediamtx-alpine:latest .
docker push netfluxio/mediamtx-alpine:latest
