name: build
run-name: Building ${{ github.ref_name }}
on:
  push:
    branches:
    - "**"
    tags:
    - "v[0-9]+*"
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        experimental: true
    - name: shellcheck
      run: shellcheck ./mise/tasks/*
    - uses: bufbuild/buf-action@v1
      with:
        push: false
        pr_comment: false
        format: true
        lint: true
        breaking: false
  backend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs:
    - lint
    steps:
    - name: install OS dependencies
      run: |
        sudo apt-get -y update && \
          sudo apt-get -y --no-install-recommends install \
            nscd \
            libx11-dev
    - name: setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
    - name: checkout
      uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        experimental: true
    - name: Setup Go 1.24.6
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.6'
        cache: false
    - name: install_goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
    - name: check_goimports
      run: mise run check_goimports
    - name: check_gomod
      run: mise run check_gomod
    - name: check_gogenerate
      run: mise run check_gogenerate
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.6
    - name: test
      run: mise run test_ci
    - name: test_integration
      run: mise run test_integration_ci
  frontend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs:
    - lint
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        experimental: true
    - name: install dependencies
      run: pnpm install
      working-directory: frontend
    - name: typescript check
      run: pnpm tsc --noEmit
      working-directory: frontend
    - name: prettier check
      run: pnpm exec prettier --single-quote --check 'src/**/*.{ts,js,scss,css,html,json}'
      working-directory: frontend
    - name: build frontend
      run: pnpm build
      working-directory: frontend
  release:
    needs:
    - lint
    - backend
    - frontend
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: install dependencies
        run: pnpm install
        working-directory: frontend
      - name: Setup Go 1.24.6
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'
      - name: install OS dependencies
        run: |
          sudo apt-get -y update && \
            sudo apt-get -y --no-install-recommends install \
              libx11-dev
      - name: log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
