name: ci-build
run-name: Building ${{ github.ref_name }}
on:
- push
- pull_request
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: ludeeus/action-shellcheck@2.0.0
  backend:
    runs-on: ubuntu-24.04
    needs:
    - lint
    steps:
    - name: install mise
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
    - name: install nscd
      run: sudo apt-get -y update && sudo apt-get -y --no-install-recommends install nscd
    - name: setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Go 1.23.5
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'
        cache: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.1
    - name: check_gomod
      run: mise run check_gomod
    - name: test_ci
      env:
        DOCKER_API_VERSION: "1.45"
      run: mise run test_ci
